// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Blob struct {
	ID          int64          `json:"id"`
	Sha256      string         `json:"sha256"`
	MediaType   string         `json:"media_type"`
	Compression string         `json:"compression"`
	SizeBytes   int64          `json:"size_bytes"`
	StorageKind string         `json:"storage_kind"`
	StoragePath sql.NullString `json:"storage_path"`
	InlineText  sql.NullString `json:"inline_text"`
	CreatedAt   string         `json:"created_at"`
}

type ClusterGroup struct {
	ID                     int64          `json:"id"`
	RepoID                 int64          `json:"repo_id"`
	StableKey              string         `json:"stable_key"`
	StableSlug             string         `json:"stable_slug"`
	Status                 string         `json:"status"`
	ClusterType            sql.NullString `json:"cluster_type"`
	RepresentativeThreadID sql.NullInt64  `json:"representative_thread_id"`
	Title                  sql.NullString `json:"title"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
	ClosedAt               sql.NullString `json:"closed_at"`
}

type ClusterRun struct {
	ID         int64          `json:"id"`
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

type Comment struct {
	ID            int64          `json:"id"`
	ThreadID      int64          `json:"thread_id"`
	GithubID      string         `json:"github_id"`
	CommentType   string         `json:"comment_type"`
	AuthorLogin   sql.NullString `json:"author_login"`
	AuthorType    sql.NullString `json:"author_type"`
	Body          string         `json:"body"`
	IsBot         int64          `json:"is_bot"`
	RawJson       string         `json:"raw_json"`
	RawJsonBlobID sql.NullInt64  `json:"raw_json_blob_id"`
	CreatedAtGh   sql.NullString `json:"created_at_gh"`
	UpdatedAtGh   sql.NullString `json:"updated_at_gh"`
}

type Document struct {
	ID         int64          `json:"id"`
	ThreadID   int64          `json:"thread_id"`
	Title      string         `json:"title"`
	Body       sql.NullString `json:"body"`
	RawText    string         `json:"raw_text"`
	DedupeText string         `json:"dedupe_text"`
	UpdatedAt  string         `json:"updated_at"`
}

type EmbeddingRun struct {
	ID         int64          `json:"id"`
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

type GithubWorkflowRun struct {
	RepoID       int64          `json:"repo_id"`
	RunID        string         `json:"run_id"`
	RunNumber    int64          `json:"run_number"`
	HeadBranch   sql.NullString `json:"head_branch"`
	HeadSha      sql.NullString `json:"head_sha"`
	Status       sql.NullString `json:"status"`
	Conclusion   sql.NullString `json:"conclusion"`
	WorkflowName sql.NullString `json:"workflow_name"`
	Event        sql.NullString `json:"event"`
	HtmlUrl      sql.NullString `json:"html_url"`
	CreatedAtGh  sql.NullString `json:"created_at_gh"`
	UpdatedAtGh  sql.NullString `json:"updated_at_gh"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

type PortableMetadatum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PullRequestCheck struct {
	ID           int64          `json:"id"`
	ThreadID     int64          `json:"thread_id"`
	Name         string         `json:"name"`
	Status       sql.NullString `json:"status"`
	Conclusion   sql.NullString `json:"conclusion"`
	DetailsUrl   sql.NullString `json:"details_url"`
	WorkflowName sql.NullString `json:"workflow_name"`
	StartedAt    sql.NullString `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

type PullRequestCommit struct {
	ThreadID    int64          `json:"thread_id"`
	Sha         string         `json:"sha"`
	Message     sql.NullString `json:"message"`
	AuthorLogin sql.NullString `json:"author_login"`
	AuthorName  sql.NullString `json:"author_name"`
	CommittedAt sql.NullString `json:"committed_at"`
	HtmlUrl     sql.NullString `json:"html_url"`
	RawJson     string         `json:"raw_json"`
	FetchedAt   string         `json:"fetched_at"`
}

type PullRequestDetail struct {
	ThreadID         int64          `json:"thread_id"`
	RepoID           int64          `json:"repo_id"`
	Number           int64          `json:"number"`
	BaseSha          sql.NullString `json:"base_sha"`
	HeadSha          sql.NullString `json:"head_sha"`
	HeadRef          sql.NullString `json:"head_ref"`
	HeadRepoFullName sql.NullString `json:"head_repo_full_name"`
	MergeableState   sql.NullString `json:"mergeable_state"`
	Additions        int64          `json:"additions"`
	Deletions        int64          `json:"deletions"`
	ChangedFiles     int64          `json:"changed_files"`
	RawJson          string         `json:"raw_json"`
	FetchedAt        string         `json:"fetched_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type PullRequestFile struct {
	ThreadID     int64          `json:"thread_id"`
	Path         string         `json:"path"`
	Status       sql.NullString `json:"status"`
	Additions    int64          `json:"additions"`
	Deletions    int64          `json:"deletions"`
	Changes      int64          `json:"changes"`
	PreviousPath sql.NullString `json:"previous_path"`
	Patch        sql.NullString `json:"patch"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

type PullRequestReviewThread struct {
	ThreadID              int64          `json:"thread_id"`
	ReviewThreadID        string         `json:"review_thread_id"`
	Path                  sql.NullString `json:"path"`
	Line                  int64          `json:"line"`
	StartLine             int64          `json:"start_line"`
	IsResolved            int64          `json:"is_resolved"`
	IsOutdated            int64          `json:"is_outdated"`
	ViewerCanResolve      int64          `json:"viewer_can_resolve"`
	ViewerCanUnresolve    int64          `json:"viewer_can_unresolve"`
	ViewerCanReply        int64          `json:"viewer_can_reply"`
	FirstAuthorLogin      sql.NullString `json:"first_author_login"`
	FirstAuthorType       sql.NullString `json:"first_author_type"`
	FirstCommentBody      sql.NullString `json:"first_comment_body"`
	FirstCommentUrl       sql.NullString `json:"first_comment_url"`
	FirstCommentCreatedAt sql.NullString `json:"first_comment_created_at"`
	FirstCommentUpdatedAt sql.NullString `json:"first_comment_updated_at"`
	CommentsJson          string         `json:"comments_json"`
	RawJson               string         `json:"raw_json"`
	FetchedAt             string         `json:"fetched_at"`
}

type PullRequestReviewThreadSync struct {
	ThreadID  int64  `json:"thread_id"`
	FetchedAt string `json:"fetched_at"`
}

type RepoSyncState struct {
	RepoID                             int64          `json:"repo_id"`
	LastFullOpenScanStartedAt          sql.NullString `json:"last_full_open_scan_started_at"`
	LastOverlappingOpenScanCompletedAt sql.NullString `json:"last_overlapping_open_scan_completed_at"`
	LastNonOverlappingScanCompletedAt  sql.NullString `json:"last_non_overlapping_scan_completed_at"`
	LastOpenCloseReconciledAt          sql.NullString `json:"last_open_close_reconciled_at"`
	UpdatedAt                          string         `json:"updated_at"`
}

type Repository struct {
	ID           int64          `json:"id"`
	Owner        string         `json:"owner"`
	Name         string         `json:"name"`
	FullName     string         `json:"full_name"`
	GithubRepoID sql.NullString `json:"github_repo_id"`
	RawJson      string         `json:"raw_json"`
	UpdatedAt    string         `json:"updated_at"`
}

type SummaryRun struct {
	ID         int64          `json:"id"`
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

type SyncRun struct {
	ID         int64          `json:"id"`
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

type Thread struct {
	ID               int64          `json:"id"`
	RepoID           int64          `json:"repo_id"`
	GithubID         string         `json:"github_id"`
	Number           int64          `json:"number"`
	Kind             string         `json:"kind"`
	State            string         `json:"state"`
	Title            string         `json:"title"`
	Body             sql.NullString `json:"body"`
	AuthorLogin      sql.NullString `json:"author_login"`
	AuthorType       sql.NullString `json:"author_type"`
	HtmlUrl          string         `json:"html_url"`
	LabelsJson       string         `json:"labels_json"`
	AssigneesJson    string         `json:"assignees_json"`
	RawJson          string         `json:"raw_json"`
	ContentHash      string         `json:"content_hash"`
	IsDraft          int64          `json:"is_draft"`
	CreatedAtGh      sql.NullString `json:"created_at_gh"`
	UpdatedAtGh      sql.NullString `json:"updated_at_gh"`
	ClosedAtGh       sql.NullString `json:"closed_at_gh"`
	MergedAtGh       sql.NullString `json:"merged_at_gh"`
	ClosedAtLocal    sql.NullString `json:"closed_at_local"`
	CloseReasonLocal sql.NullString `json:"close_reason_local"`
	FirstPulledAt    sql.NullString `json:"first_pulled_at"`
	LastPulledAt     sql.NullString `json:"last_pulled_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type ThreadKeySummary struct {
	ID               int64  `json:"id"`
	ThreadRevisionID int64  `json:"thread_revision_id"`
	SummaryKind      string `json:"summary_kind"`
	PromptVersion    string `json:"prompt_version"`
	Provider         string `json:"provider"`
	Model            string `json:"model"`
	InputHash        string `json:"input_hash"`
	OutputHash       string `json:"output_hash"`
	KeyText          string `json:"key_text"`
	CreatedAt        string `json:"created_at"`
}

type ThreadRevision struct {
	ID              int64          `json:"id"`
	ThreadID        int64          `json:"thread_id"`
	SourceUpdatedAt sql.NullString `json:"source_updated_at"`
	ContentHash     string         `json:"content_hash"`
	TitleHash       string         `json:"title_hash"`
	BodyHash        string         `json:"body_hash"`
	LabelsHash      string         `json:"labels_hash"`
	RawJsonBlobID   sql.NullInt64  `json:"raw_json_blob_id"`
	CreatedAt       string         `json:"created_at"`
}

type ThreadVector struct {
	ThreadID      int64  `json:"thread_id"`
	Basis         string `json:"basis"`
	Model         string `json:"model"`
	Dimensions    int64  `json:"dimensions"`
	ContentHash   string `json:"content_hash"`
	VectorJson    string `json:"vector_json"`
	VectorBackend string `json:"vector_backend"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}
