// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const closeThreadLocally = `-- name: CloseThreadLocally :execrows
update threads
set closed_at_local = ?1, close_reason_local = ?2, updated_at = ?1
where repo_id = ?3 and number = ?4
`

type CloseThreadLocallyParams struct {
	ClosedAt sql.NullString `json:"closed_at"`
	Reason   sql.NullString `json:"reason"`
	RepoID   int64          `json:"repo_id"`
	Number   int64          `json:"number"`
}

func (q *Queries) CloseThreadLocally(ctx context.Context, arg CloseThreadLocallyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeThreadLocally,
		arg.ClosedAt,
		arg.Reason,
		arg.RepoID,
		arg.Number,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countClusters = `-- name: CountClusters :one
select count(*) from cluster_groups
`

func (q *Queries) CountClusters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClusters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenThreads = `-- name: CountOpenThreads :one
select count(*) from threads where state = 'open' and closed_at_local is null
`

func (q *Queries) CountOpenThreads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenThreads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepositories = `-- name: CountRepositories :one
select count(*) from repositories
`

func (q *Queries) CountRepositories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepositories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreads = `-- name: CountThreads :one
select count(*) from threads
`

func (q *Queries) CountThreads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countThreads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePullRequestChecks = `-- name: DeletePullRequestChecks :exec
delete from pull_request_checks where thread_id = ?1
`

func (q *Queries) DeletePullRequestChecks(ctx context.Context, threadID int64) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestChecks, threadID)
	return err
}

const deletePullRequestCommits = `-- name: DeletePullRequestCommits :exec
delete from pull_request_commits where thread_id = ?1
`

func (q *Queries) DeletePullRequestCommits(ctx context.Context, threadID int64) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestCommits, threadID)
	return err
}

const deletePullRequestFiles = `-- name: DeletePullRequestFiles :exec
delete from pull_request_files where thread_id = ?1
`

func (q *Queries) DeletePullRequestFiles(ctx context.Context, threadID int64) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestFiles, threadID)
	return err
}

const deletePullRequestReviewThreads = `-- name: DeletePullRequestReviewThreads :exec
delete from pull_request_review_threads where thread_id = ?1
`

func (q *Queries) DeletePullRequestReviewThreads(ctx context.Context, threadID int64) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestReviewThreads, threadID)
	return err
}

const insertPullRequestCheck = `-- name: InsertPullRequestCheck :exec
insert into pull_request_checks(thread_id, name, status, conclusion, details_url, workflow_name, started_at, completed_at, raw_json, fetched_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type InsertPullRequestCheckParams struct {
	ThreadID     int64          `json:"thread_id"`
	Name         string         `json:"name"`
	Status       sql.NullString `json:"status"`
	Conclusion   sql.NullString `json:"conclusion"`
	DetailsUrl   sql.NullString `json:"details_url"`
	WorkflowName sql.NullString `json:"workflow_name"`
	StartedAt    sql.NullString `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

func (q *Queries) InsertPullRequestCheck(ctx context.Context, arg InsertPullRequestCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertPullRequestCheck,
		arg.ThreadID,
		arg.Name,
		arg.Status,
		arg.Conclusion,
		arg.DetailsUrl,
		arg.WorkflowName,
		arg.StartedAt,
		arg.CompletedAt,
		arg.RawJson,
		arg.FetchedAt,
	)
	return err
}

const insertPullRequestCommit = `-- name: InsertPullRequestCommit :exec
insert into pull_request_commits(thread_id, sha, message, author_login, author_name, committed_at, html_url, raw_json, fetched_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertPullRequestCommitParams struct {
	ThreadID    int64          `json:"thread_id"`
	Sha         string         `json:"sha"`
	Message     sql.NullString `json:"message"`
	AuthorLogin sql.NullString `json:"author_login"`
	AuthorName  sql.NullString `json:"author_name"`
	CommittedAt sql.NullString `json:"committed_at"`
	HtmlUrl     sql.NullString `json:"html_url"`
	RawJson     string         `json:"raw_json"`
	FetchedAt   string         `json:"fetched_at"`
}

func (q *Queries) InsertPullRequestCommit(ctx context.Context, arg InsertPullRequestCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertPullRequestCommit,
		arg.ThreadID,
		arg.Sha,
		arg.Message,
		arg.AuthorLogin,
		arg.AuthorName,
		arg.CommittedAt,
		arg.HtmlUrl,
		arg.RawJson,
		arg.FetchedAt,
	)
	return err
}

const insertPullRequestFile = `-- name: InsertPullRequestFile :exec
insert into pull_request_files(thread_id, path, status, additions, deletions, changes, previous_path, patch, raw_json, fetched_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type InsertPullRequestFileParams struct {
	ThreadID     int64          `json:"thread_id"`
	Path         string         `json:"path"`
	Status       sql.NullString `json:"status"`
	Additions    int64          `json:"additions"`
	Deletions    int64          `json:"deletions"`
	Changes      int64          `json:"changes"`
	PreviousPath sql.NullString `json:"previous_path"`
	Patch        sql.NullString `json:"patch"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

func (q *Queries) InsertPullRequestFile(ctx context.Context, arg InsertPullRequestFileParams) error {
	_, err := q.db.ExecContext(ctx, insertPullRequestFile,
		arg.ThreadID,
		arg.Path,
		arg.Status,
		arg.Additions,
		arg.Deletions,
		arg.Changes,
		arg.PreviousPath,
		arg.Patch,
		arg.RawJson,
		arg.FetchedAt,
	)
	return err
}

const lastSuccessfulListSyncAt = `-- name: LastSuccessfulListSyncAt :one
select cast(coalesce(max(finished_at), '') as text) as last_sync
from sync_runs
where repo_id = ?1
  and status in ('success', 'completed')
  and (
    (?2 = 'open' and scope in ('open', 'all')) or
    (?2 = 'closed' and scope in ('closed', 'all')) or
    (?2 = 'all' and scope = 'all')
  )
`

type LastSuccessfulListSyncAtParams struct {
	RepoID int64       `json:"repo_id"`
	State  interface{} `json:"state"`
}

func (q *Queries) LastSuccessfulListSyncAt(ctx context.Context, arg LastSuccessfulListSyncAtParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessfulListSyncAt, arg.RepoID, arg.State)
	var last_sync string
	err := row.Scan(&last_sync)
	return last_sync, err
}

const lastSuccessfulSyncAt = `-- name: LastSuccessfulSyncAt :one
select cast(coalesce(max(finished_at), '') as text) as last_sync
from sync_runs
where repo_id = ?1 and status in ('success', 'completed')
`

func (q *Queries) LastSuccessfulSyncAt(ctx context.Context, repoID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessfulSyncAt, repoID)
	var last_sync string
	err := row.Scan(&last_sync)
	return last_sync, err
}

const listClusterRuns = `-- name: ListClusterRuns :many
select id, repo_id, scope, status, started_at, finished_at, stats_json, error_text
from cluster_runs
where repo_id = ?1
order by id desc
limit ?2
`

type ListClusterRunsParams struct {
	RepoID   int64 `json:"repo_id"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) ListClusterRuns(ctx context.Context, arg ListClusterRunsParams) ([]ClusterRun, error) {
	rows, err := q.db.QueryContext(ctx, listClusterRuns, arg.RepoID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClusterRun
	for rows.Next() {
		var i ClusterRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Scope,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StatsJson,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
select id, thread_id, github_id, comment_type, author_login, author_type, body, is_bot, raw_json, created_at_gh, updated_at_gh
from comments
where thread_id = ?1
order by created_at_gh, id
`

type ListCommentsRow struct {
	ID          int64          `json:"id"`
	ThreadID    int64          `json:"thread_id"`
	GithubID    string         `json:"github_id"`
	CommentType string         `json:"comment_type"`
	AuthorLogin sql.NullString `json:"author_login"`
	AuthorType  sql.NullString `json:"author_type"`
	Body        string         `json:"body"`
	IsBot       int64          `json:"is_bot"`
	RawJson     string         `json:"raw_json"`
	CreatedAtGh sql.NullString `json:"created_at_gh"`
	UpdatedAtGh sql.NullString `json:"updated_at_gh"`
}

func (q *Queries) ListComments(ctx context.Context, threadID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.GithubID,
			&i.CommentType,
			&i.AuthorLogin,
			&i.AuthorType,
			&i.Body,
			&i.IsBot,
			&i.RawJson,
			&i.CreatedAtGh,
			&i.UpdatedAtGh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingRuns = `-- name: ListEmbeddingRuns :many
select id, repo_id, scope, status, started_at, finished_at, stats_json, error_text
from embedding_runs
where repo_id = ?1
order by id desc
limit ?2
`

type ListEmbeddingRunsParams struct {
	RepoID   int64 `json:"repo_id"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) ListEmbeddingRuns(ctx context.Context, arg ListEmbeddingRunsParams) ([]EmbeddingRun, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingRuns, arg.RepoID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmbeddingRun
	for rows.Next() {
		var i EmbeddingRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Scope,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StatsJson,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingTasks = `-- name: ListEmbeddingTasks :many
select t.id, t.number, t.kind, t.title, coalesce(d.body, t.body, '') as body, coalesce(d.raw_text, t.body, '') as raw_text,
  coalesce(d.dedupe_text, t.title || ' ' || coalesce(t.body, '')) as dedupe_text,
  cast(coalesce((
    select tks.key_text
    from thread_key_summaries tks
    join thread_revisions tr on tr.id = tks.thread_revision_id
    where tr.thread_id = t.id
      and tks.summary_kind in ('llm_key_summary', 'llm_key_3line')
    order by tks.created_at desc, tr.created_at desc, tks.id desc
    limit 1
  ), '') as text) as key_summary,
  coalesce(tv.content_hash, '') as existing_hash
from threads t
left join documents d on d.thread_id = t.id
left join thread_vectors tv on tv.thread_id = t.id and tv.basis = ?1 and tv.model = ?2
where t.repo_id = ?3
  and (?4 != 0 or (t.state = 'open' and t.closed_at_local is null))
  and (?5 is null or t.number = ?5)
order by coalesce(t.updated_at_gh, t.updated_at) desc, t.number desc
limit case when ?6 <= 0 then -1 else ?6 end
`

type ListEmbeddingTasksParams struct {
	Basis         string      `json:"basis"`
	Model         string      `json:"model"`
	RepoID        int64       `json:"repo_id"`
	IncludeClosed interface{} `json:"include_closed"`
	Number        interface{} `json:"number"`
	RowLimit      interface{} `json:"row_limit"`
}

type ListEmbeddingTasksRow struct {
	ID           int64  `json:"id"`
	Number       int64  `json:"number"`
	Kind         string `json:"kind"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	RawText      string `json:"raw_text"`
	DedupeText   string `json:"dedupe_text"`
	KeySummary   string `json:"key_summary"`
	ExistingHash string `json:"existing_hash"`
}

func (q *Queries) ListEmbeddingTasks(ctx context.Context, arg ListEmbeddingTasksParams) ([]ListEmbeddingTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingTasks,
		arg.Basis,
		arg.Model,
		arg.RepoID,
		arg.IncludeClosed,
		arg.Number,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmbeddingTasksRow
	for rows.Next() {
		var i ListEmbeddingTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.RawText,
			&i.DedupeText,
			&i.KeySummary,
			&i.ExistingHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
select id, owner, name, full_name, github_repo_id, coalesce(raw_json, '') as raw_json, updated_at
from repositories
order by coalesce(updated_at, '') desc, id desc
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.GithubRepoID,
			&i.RawJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaryRuns = `-- name: ListSummaryRuns :many
select id, repo_id, scope, status, started_at, finished_at, stats_json, error_text
from summary_runs
where repo_id = ?1
order by id desc
limit ?2
`

type ListSummaryRunsParams struct {
	RepoID   int64 `json:"repo_id"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) ListSummaryRuns(ctx context.Context, arg ListSummaryRunsParams) ([]SummaryRun, error) {
	rows, err := q.db.QueryContext(ctx, listSummaryRuns, arg.RepoID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryRun
	for rows.Next() {
		var i SummaryRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Scope,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StatsJson,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRuns = `-- name: ListSyncRuns :many
select id, repo_id, scope, status, started_at, finished_at, stats_json, error_text
from sync_runs
where repo_id = ?1
order by id desc
limit ?2
`

type ListSyncRunsParams struct {
	RepoID   int64 `json:"repo_id"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) ListSyncRuns(ctx context.Context, arg ListSyncRunsParams) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRuns, arg.RepoID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncRun
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Scope,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StatsJson,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsCurrentSchema = `-- name: ListThreadsCurrentSchema :many
select id, repo_id, github_id, number, kind, state, title, body, author_login, author_type, html_url,
  labels_json, assignees_json, coalesce(raw_json, '') as raw_json, content_hash, is_draft, created_at_gh, updated_at_gh,
  closed_at_gh, merged_at_gh, first_pulled_at, last_pulled_at, updated_at, closed_at_local, close_reason_local
from threads
where repo_id = ?1
  and (?2 != 0 or closed_at_local is null)
order by number
limit case when ?3 <= 0 then -1 else ?3 end
`

type ListThreadsCurrentSchemaParams struct {
	RepoID        int64       `json:"repo_id"`
	IncludeClosed interface{} `json:"include_closed"`
	RowLimit      interface{} `json:"row_limit"`
}

type ListThreadsCurrentSchemaRow struct {
	ID               int64          `json:"id"`
	RepoID           int64          `json:"repo_id"`
	GithubID         string         `json:"github_id"`
	Number           int64          `json:"number"`
	Kind             string         `json:"kind"`
	State            string         `json:"state"`
	Title            string         `json:"title"`
	Body             sql.NullString `json:"body"`
	AuthorLogin      sql.NullString `json:"author_login"`
	AuthorType       sql.NullString `json:"author_type"`
	HtmlUrl          string         `json:"html_url"`
	LabelsJson       string         `json:"labels_json"`
	AssigneesJson    string         `json:"assignees_json"`
	RawJson          string         `json:"raw_json"`
	ContentHash      string         `json:"content_hash"`
	IsDraft          int64          `json:"is_draft"`
	CreatedAtGh      sql.NullString `json:"created_at_gh"`
	UpdatedAtGh      sql.NullString `json:"updated_at_gh"`
	ClosedAtGh       sql.NullString `json:"closed_at_gh"`
	MergedAtGh       sql.NullString `json:"merged_at_gh"`
	FirstPulledAt    sql.NullString `json:"first_pulled_at"`
	LastPulledAt     sql.NullString `json:"last_pulled_at"`
	UpdatedAt        string         `json:"updated_at"`
	ClosedAtLocal    sql.NullString `json:"closed_at_local"`
	CloseReasonLocal sql.NullString `json:"close_reason_local"`
}

func (q *Queries) ListThreadsCurrentSchema(ctx context.Context, arg ListThreadsCurrentSchemaParams) ([]ListThreadsCurrentSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsCurrentSchema, arg.RepoID, arg.IncludeClosed, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsCurrentSchemaRow
	for rows.Next() {
		var i ListThreadsCurrentSchemaRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.GithubID,
			&i.Number,
			&i.Kind,
			&i.State,
			&i.Title,
			&i.Body,
			&i.AuthorLogin,
			&i.AuthorType,
			&i.HtmlUrl,
			&i.LabelsJson,
			&i.AssigneesJson,
			&i.RawJson,
			&i.ContentHash,
			&i.IsDraft,
			&i.CreatedAtGh,
			&i.UpdatedAtGh,
			&i.ClosedAtGh,
			&i.MergedAtGh,
			&i.FirstPulledAt,
			&i.LastPulledAt,
			&i.UpdatedAt,
			&i.ClosedAtLocal,
			&i.CloseReasonLocal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
select repo_id, run_id, run_number, head_branch, head_sha, status, conclusion, workflow_name, event, html_url, created_at_gh, updated_at_gh, raw_json, fetched_at
from github_workflow_runs
where repo_id = ?1
  and (?2 is null or head_branch = ?2)
  and (?3 is null or head_sha = ?3)
order by updated_at_gh desc, run_id desc
limit ?4
`

type ListWorkflowRunsParams struct {
	RepoID     int64       `json:"repo_id"`
	HeadBranch interface{} `json:"head_branch"`
	HeadSha    interface{} `json:"head_sha"`
	RowLimit   int64       `json:"row_limit"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]GithubWorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRuns,
		arg.RepoID,
		arg.HeadBranch,
		arg.HeadSha,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubWorkflowRun
	for rows.Next() {
		var i GithubWorkflowRun
		if err := rows.Scan(
			&i.RepoID,
			&i.RunID,
			&i.RunNumber,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Status,
			&i.Conclusion,
			&i.WorkflowName,
			&i.Event,
			&i.HtmlUrl,
			&i.CreatedAtGh,
			&i.UpdatedAtGh,
			&i.RawJson,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOpenThreadClosedFromGitHub = `-- name: MarkOpenThreadClosedFromGitHub :execrows
update threads
set github_id = ?1,
  state = ?2,
  title = ?3,
  body = ?4,
  author_login = ?5,
  author_type = ?6,
  html_url = ?7,
  labels_json = ?8,
  assignees_json = ?9,
  raw_json = ?10,
  content_hash = ?11,
  is_draft = ?12,
  created_at_gh = ?13,
  updated_at_gh = ?14,
  closed_at_gh = ?15,
  merged_at_gh = ?16,
  last_pulled_at = ?17,
  updated_at = ?18
where repo_id = ?19
  and kind = ?20
  and number = ?21
  and state = 'open'
  and closed_at_local is null
`

type MarkOpenThreadClosedFromGitHubParams struct {
	GithubID      string         `json:"github_id"`
	State         string         `json:"state"`
	Title         string         `json:"title"`
	Body          sql.NullString `json:"body"`
	AuthorLogin   sql.NullString `json:"author_login"`
	AuthorType    sql.NullString `json:"author_type"`
	HtmlUrl       string         `json:"html_url"`
	LabelsJson    string         `json:"labels_json"`
	AssigneesJson string         `json:"assignees_json"`
	RawJson       string         `json:"raw_json"`
	ContentHash   string         `json:"content_hash"`
	IsDraft       int64          `json:"is_draft"`
	CreatedAtGh   sql.NullString `json:"created_at_gh"`
	UpdatedAtGh   sql.NullString `json:"updated_at_gh"`
	ClosedAtGh    sql.NullString `json:"closed_at_gh"`
	MergedAtGh    sql.NullString `json:"merged_at_gh"`
	LastPulledAt  sql.NullString `json:"last_pulled_at"`
	UpdatedAt     string         `json:"updated_at"`
	RepoID        int64          `json:"repo_id"`
	Kind          string         `json:"kind"`
	Number        int64          `json:"number"`
}

func (q *Queries) MarkOpenThreadClosedFromGitHub(ctx context.Context, arg MarkOpenThreadClosedFromGitHubParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOpenThreadClosedFromGitHub,
		arg.GithubID,
		arg.State,
		arg.Title,
		arg.Body,
		arg.AuthorLogin,
		arg.AuthorType,
		arg.HtmlUrl,
		arg.LabelsJson,
		arg.AssigneesJson,
		arg.RawJson,
		arg.ContentHash,
		arg.IsDraft,
		arg.CreatedAtGh,
		arg.UpdatedAtGh,
		arg.ClosedAtGh,
		arg.MergedAtGh,
		arg.LastPulledAt,
		arg.UpdatedAt,
		arg.RepoID,
		arg.Kind,
		arg.Number,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const maxSuccessfulSyncFinishedAt = `-- name: MaxSuccessfulSyncFinishedAt :one
select cast(coalesce(max(finished_at), '') as text) as last_sync from sync_runs where status in ('success', 'completed')
`

func (q *Queries) MaxSuccessfulSyncFinishedAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, maxSuccessfulSyncFinishedAt)
	var last_sync string
	err := row.Scan(&last_sync)
	return last_sync, err
}

const portableExportedAt = `-- name: PortableExportedAt :one
select value from portable_metadata where key = 'exported_at'
`

func (q *Queries) PortableExportedAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, portableExportedAt)
	var value string
	err := row.Scan(&value)
	return value, err
}

const pullRequestChecks = `-- name: PullRequestChecks :many
select id, thread_id, name, status, conclusion, details_url, workflow_name, started_at, completed_at, raw_json, fetched_at
from pull_request_checks
where thread_id = ?1
order by name
`

func (q *Queries) PullRequestChecks(ctx context.Context, threadID int64) ([]PullRequestCheck, error) {
	rows, err := q.db.QueryContext(ctx, pullRequestChecks, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestCheck
	for rows.Next() {
		var i PullRequestCheck
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Name,
			&i.Status,
			&i.Conclusion,
			&i.DetailsUrl,
			&i.WorkflowName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RawJson,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullRequestCommits = `-- name: PullRequestCommits :many
select thread_id, sha, message, author_login, author_name, committed_at, html_url, raw_json, fetched_at
from pull_request_commits
where thread_id = ?1
order by rowid
`

func (q *Queries) PullRequestCommits(ctx context.Context, threadID int64) ([]PullRequestCommit, error) {
	rows, err := q.db.QueryContext(ctx, pullRequestCommits, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestCommit
	for rows.Next() {
		var i PullRequestCommit
		if err := rows.Scan(
			&i.ThreadID,
			&i.Sha,
			&i.Message,
			&i.AuthorLogin,
			&i.AuthorName,
			&i.CommittedAt,
			&i.HtmlUrl,
			&i.RawJson,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullRequestDetail = `-- name: PullRequestDetail :one
select thread_id, repo_id, number, base_sha, head_sha, head_ref, head_repo_full_name, mergeable_state, additions, deletions, changed_files, raw_json, fetched_at, updated_at
from pull_request_details
where repo_id = ?1 and number = ?2
`

type PullRequestDetailParams struct {
	RepoID int64 `json:"repo_id"`
	Number int64 `json:"number"`
}

func (q *Queries) PullRequestDetail(ctx context.Context, arg PullRequestDetailParams) (PullRequestDetail, error) {
	row := q.db.QueryRowContext(ctx, pullRequestDetail, arg.RepoID, arg.Number)
	var i PullRequestDetail
	err := row.Scan(
		&i.ThreadID,
		&i.RepoID,
		&i.Number,
		&i.BaseSha,
		&i.HeadSha,
		&i.HeadRef,
		&i.HeadRepoFullName,
		&i.MergeableState,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.RawJson,
		&i.FetchedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pullRequestFiles = `-- name: PullRequestFiles :many
select thread_id, path, status, additions, deletions, changes, previous_path, patch, raw_json, fetched_at
from pull_request_files
where thread_id = ?1
order by path
`

func (q *Queries) PullRequestFiles(ctx context.Context, threadID int64) ([]PullRequestFile, error) {
	rows, err := q.db.QueryContext(ctx, pullRequestFiles, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestFile
	for rows.Next() {
		var i PullRequestFile
		if err := rows.Scan(
			&i.ThreadID,
			&i.Path,
			&i.Status,
			&i.Additions,
			&i.Deletions,
			&i.Changes,
			&i.PreviousPath,
			&i.Patch,
			&i.RawJson,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullRequestReviewThreads = `-- name: PullRequestReviewThreads :many
select thread_id, review_thread_id, path, line, start_line, is_resolved, is_outdated,
  viewer_can_resolve, viewer_can_unresolve, viewer_can_reply,
  first_author_login, first_author_type, first_comment_body, first_comment_url,
  first_comment_created_at, first_comment_updated_at, comments_json, raw_json, fetched_at
from pull_request_review_threads
where thread_id = ?1
order by is_resolved, path, line, review_thread_id
`

func (q *Queries) PullRequestReviewThreads(ctx context.Context, threadID int64) ([]PullRequestReviewThread, error) {
	rows, err := q.db.QueryContext(ctx, pullRequestReviewThreads, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestReviewThread
	for rows.Next() {
		var i PullRequestReviewThread
		if err := rows.Scan(
			&i.ThreadID,
			&i.ReviewThreadID,
			&i.Path,
			&i.Line,
			&i.StartLine,
			&i.IsResolved,
			&i.IsOutdated,
			&i.ViewerCanResolve,
			&i.ViewerCanUnresolve,
			&i.ViewerCanReply,
			&i.FirstAuthorLogin,
			&i.FirstAuthorType,
			&i.FirstCommentBody,
			&i.FirstCommentUrl,
			&i.FirstCommentCreatedAt,
			&i.FirstCommentUpdatedAt,
			&i.CommentsJson,
			&i.RawJson,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullRequestReviewThreadsFetchedAt = `-- name: PullRequestReviewThreadsFetchedAt :one
select fetched_at from pull_request_review_thread_syncs where thread_id = ?1
`

func (q *Queries) PullRequestReviewThreadsFetchedAt(ctx context.Context, threadID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, pullRequestReviewThreadsFetchedAt, threadID)
	var fetched_at string
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const recordClusterRun = `-- name: RecordClusterRun :one
insert into cluster_runs(repo_id, scope, status, started_at, finished_at, stats_json, error_text)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7)
returning id
`

type RecordClusterRunParams struct {
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

func (q *Queries) RecordClusterRun(ctx context.Context, arg RecordClusterRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordClusterRun,
		arg.RepoID,
		arg.Scope,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.StatsJson,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordEmbeddingRun = `-- name: RecordEmbeddingRun :one
insert into embedding_runs(repo_id, scope, status, started_at, finished_at, stats_json, error_text)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7)
returning id
`

type RecordEmbeddingRunParams struct {
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

func (q *Queries) RecordEmbeddingRun(ctx context.Context, arg RecordEmbeddingRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordEmbeddingRun,
		arg.RepoID,
		arg.Scope,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.StatsJson,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordSummaryRun = `-- name: RecordSummaryRun :one
insert into summary_runs(repo_id, scope, status, started_at, finished_at, stats_json, error_text)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7)
returning id
`

type RecordSummaryRunParams struct {
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

func (q *Queries) RecordSummaryRun(ctx context.Context, arg RecordSummaryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordSummaryRun,
		arg.RepoID,
		arg.Scope,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.StatsJson,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordSyncRun = `-- name: RecordSyncRun :one
insert into sync_runs(repo_id, scope, status, started_at, finished_at, stats_json, error_text)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7)
returning id
`

type RecordSyncRunParams struct {
	RepoID     int64          `json:"repo_id"`
	Scope      string         `json:"scope"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	StatsJson  sql.NullString `json:"stats_json"`
	ErrorText  sql.NullString `json:"error_text"`
}

func (q *Queries) RecordSyncRun(ctx context.Context, arg RecordSyncRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordSyncRun,
		arg.RepoID,
		arg.Scope,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.StatsJson,
		arg.ErrorText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const reopenThreadLocally = `-- name: ReopenThreadLocally :execrows
update threads
set closed_at_local = null, close_reason_local = null, updated_at = ?1
where repo_id = ?2 and number = ?3
`

type ReopenThreadLocallyParams struct {
	UpdatedAt string `json:"updated_at"`
	RepoID    int64  `json:"repo_id"`
	Number    int64  `json:"number"`
}

func (q *Queries) ReopenThreadLocally(ctx context.Context, arg ReopenThreadLocallyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenThreadLocally, arg.UpdatedAt, arg.RepoID, arg.Number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const repoSyncStateLastSync = `-- name: RepoSyncStateLastSync :one
select cast(coalesce(
  max(last_open_close_reconciled_at),
  max(last_overlapping_open_scan_completed_at),
  max(last_non_overlapping_scan_completed_at),
  max(last_full_open_scan_started_at),
  max(updated_at),
  ''
) as text) as last_sync from repo_sync_state
`

func (q *Queries) RepoSyncStateLastSync(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, repoSyncStateLastSync)
	var last_sync string
	err := row.Scan(&last_sync)
	return last_sync, err
}

const repositoryByFullName = `-- name: RepositoryByFullName :one
select id, owner, name, full_name, github_repo_id, coalesce(raw_json, '') as raw_json, updated_at
from repositories
where full_name = ?1
`

func (q *Queries) RepositoryByFullName(ctx context.Context, fullName string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, repositoryByFullName, fullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.GithubRepoID,
		&i.RawJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertComment = `-- name: UpsertComment :one
insert into comments(thread_id, github_id, comment_type, author_login, author_type, body, is_bot, raw_json, created_at_gh, updated_at_gh)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
on conflict(thread_id, comment_type, github_id) do update set
  author_login=excluded.author_login,
  author_type=excluded.author_type,
  body=excluded.body,
  is_bot=excluded.is_bot,
  raw_json=excluded.raw_json,
  created_at_gh=excluded.created_at_gh,
  updated_at_gh=excluded.updated_at_gh
returning id
`

type UpsertCommentParams struct {
	ThreadID    int64          `json:"thread_id"`
	GithubID    string         `json:"github_id"`
	CommentType string         `json:"comment_type"`
	AuthorLogin sql.NullString `json:"author_login"`
	AuthorType  sql.NullString `json:"author_type"`
	Body        string         `json:"body"`
	IsBot       int64          `json:"is_bot"`
	RawJson     string         `json:"raw_json"`
	CreatedAtGh sql.NullString `json:"created_at_gh"`
	UpdatedAtGh sql.NullString `json:"updated_at_gh"`
}

func (q *Queries) UpsertComment(ctx context.Context, arg UpsertCommentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertComment,
		arg.ThreadID,
		arg.GithubID,
		arg.CommentType,
		arg.AuthorLogin,
		arg.AuthorType,
		arg.Body,
		arg.IsBot,
		arg.RawJson,
		arg.CreatedAtGh,
		arg.UpdatedAtGh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocument = `-- name: UpsertDocument :one
insert into documents(thread_id, title, body, raw_text, dedupe_text, updated_at)
values(?1, ?2, ?3, ?4, ?5, ?6)
on conflict(thread_id) do update set
  title=excluded.title,
  body=excluded.body,
  raw_text=excluded.raw_text,
  dedupe_text=excluded.dedupe_text,
  updated_at=excluded.updated_at
returning id
`

type UpsertDocumentParams struct {
	ThreadID   int64          `json:"thread_id"`
	Title      string         `json:"title"`
	Body       sql.NullString `json:"body"`
	RawText    string         `json:"raw_text"`
	DedupeText string         `json:"dedupe_text"`
	UpdatedAt  string         `json:"updated_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.ThreadID,
		arg.Title,
		arg.Body,
		arg.RawText,
		arg.DedupeText,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertPullRequestDetail = `-- name: UpsertPullRequestDetail :exec
insert into pull_request_details(thread_id, repo_id, number, base_sha, head_sha, head_ref, head_repo_full_name, mergeable_state, additions, deletions, changed_files, raw_json, fetched_at, updated_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
on conflict(thread_id) do update set
  repo_id=excluded.repo_id,
  number=excluded.number,
  base_sha=excluded.base_sha,
  head_sha=excluded.head_sha,
  head_ref=excluded.head_ref,
  head_repo_full_name=excluded.head_repo_full_name,
  mergeable_state=excluded.mergeable_state,
  additions=excluded.additions,
  deletions=excluded.deletions,
  changed_files=excluded.changed_files,
  raw_json=excluded.raw_json,
  fetched_at=excluded.fetched_at,
  updated_at=excluded.updated_at
`

type UpsertPullRequestDetailParams struct {
	ThreadID         int64          `json:"thread_id"`
	RepoID           int64          `json:"repo_id"`
	Number           int64          `json:"number"`
	BaseSha          sql.NullString `json:"base_sha"`
	HeadSha          sql.NullString `json:"head_sha"`
	HeadRef          sql.NullString `json:"head_ref"`
	HeadRepoFullName sql.NullString `json:"head_repo_full_name"`
	MergeableState   sql.NullString `json:"mergeable_state"`
	Additions        int64          `json:"additions"`
	Deletions        int64          `json:"deletions"`
	ChangedFiles     int64          `json:"changed_files"`
	RawJson          string         `json:"raw_json"`
	FetchedAt        string         `json:"fetched_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) UpsertPullRequestDetail(ctx context.Context, arg UpsertPullRequestDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestDetail,
		arg.ThreadID,
		arg.RepoID,
		arg.Number,
		arg.BaseSha,
		arg.HeadSha,
		arg.HeadRef,
		arg.HeadRepoFullName,
		arg.MergeableState,
		arg.Additions,
		arg.Deletions,
		arg.ChangedFiles,
		arg.RawJson,
		arg.FetchedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertPullRequestReviewThread = `-- name: UpsertPullRequestReviewThread :exec
insert into pull_request_review_threads(
  thread_id, review_thread_id, path, line, start_line, is_resolved, is_outdated,
  viewer_can_resolve, viewer_can_unresolve, viewer_can_reply,
  first_author_login, first_author_type, first_comment_body, first_comment_url,
  first_comment_created_at, first_comment_updated_at, comments_json, raw_json, fetched_at
)
values(
  ?1, ?2, ?3, ?4, ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12, ?13, ?14,
  ?15, ?16, ?17, ?18, ?19
)
on conflict(thread_id, review_thread_id) do update set
  path=excluded.path,
  line=excluded.line,
  start_line=excluded.start_line,
  is_resolved=excluded.is_resolved,
  is_outdated=excluded.is_outdated,
  viewer_can_resolve=excluded.viewer_can_resolve,
  viewer_can_unresolve=excluded.viewer_can_unresolve,
  viewer_can_reply=excluded.viewer_can_reply,
  first_author_login=excluded.first_author_login,
  first_author_type=excluded.first_author_type,
  first_comment_body=excluded.first_comment_body,
  first_comment_url=excluded.first_comment_url,
  first_comment_created_at=excluded.first_comment_created_at,
  first_comment_updated_at=excluded.first_comment_updated_at,
  comments_json=excluded.comments_json,
  raw_json=excluded.raw_json,
  fetched_at=excluded.fetched_at
`

type UpsertPullRequestReviewThreadParams struct {
	ThreadID              int64          `json:"thread_id"`
	ReviewThreadID        string         `json:"review_thread_id"`
	Path                  sql.NullString `json:"path"`
	Line                  int64          `json:"line"`
	StartLine             int64          `json:"start_line"`
	IsResolved            int64          `json:"is_resolved"`
	IsOutdated            int64          `json:"is_outdated"`
	ViewerCanResolve      int64          `json:"viewer_can_resolve"`
	ViewerCanUnresolve    int64          `json:"viewer_can_unresolve"`
	ViewerCanReply        int64          `json:"viewer_can_reply"`
	FirstAuthorLogin      sql.NullString `json:"first_author_login"`
	FirstAuthorType       sql.NullString `json:"first_author_type"`
	FirstCommentBody      sql.NullString `json:"first_comment_body"`
	FirstCommentUrl       sql.NullString `json:"first_comment_url"`
	FirstCommentCreatedAt sql.NullString `json:"first_comment_created_at"`
	FirstCommentUpdatedAt sql.NullString `json:"first_comment_updated_at"`
	CommentsJson          string         `json:"comments_json"`
	RawJson               string         `json:"raw_json"`
	FetchedAt             string         `json:"fetched_at"`
}

func (q *Queries) UpsertPullRequestReviewThread(ctx context.Context, arg UpsertPullRequestReviewThreadParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestReviewThread,
		arg.ThreadID,
		arg.ReviewThreadID,
		arg.Path,
		arg.Line,
		arg.StartLine,
		arg.IsResolved,
		arg.IsOutdated,
		arg.ViewerCanResolve,
		arg.ViewerCanUnresolve,
		arg.ViewerCanReply,
		arg.FirstAuthorLogin,
		arg.FirstAuthorType,
		arg.FirstCommentBody,
		arg.FirstCommentUrl,
		arg.FirstCommentCreatedAt,
		arg.FirstCommentUpdatedAt,
		arg.CommentsJson,
		arg.RawJson,
		arg.FetchedAt,
	)
	return err
}

const upsertPullRequestReviewThreadSync = `-- name: UpsertPullRequestReviewThreadSync :exec
insert into pull_request_review_thread_syncs(thread_id, fetched_at)
values(?1, ?2)
on conflict(thread_id) do update set fetched_at=excluded.fetched_at
`

type UpsertPullRequestReviewThreadSyncParams struct {
	ThreadID  int64  `json:"thread_id"`
	FetchedAt string `json:"fetched_at"`
}

func (q *Queries) UpsertPullRequestReviewThreadSync(ctx context.Context, arg UpsertPullRequestReviewThreadSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestReviewThreadSync, arg.ThreadID, arg.FetchedAt)
	return err
}

const upsertRepository = `-- name: UpsertRepository :one
insert into repositories(owner, name, full_name, github_repo_id, raw_json, updated_at)
values(?1, ?2, ?3, ?4, ?5, ?6)
on conflict(full_name) do update set
  owner=excluded.owner,
  name=excluded.name,
  github_repo_id=excluded.github_repo_id,
  raw_json=excluded.raw_json,
  updated_at=excluded.updated_at
returning id
`

type UpsertRepositoryParams struct {
	Owner        string         `json:"owner"`
	Name         string         `json:"name"`
	FullName     string         `json:"full_name"`
	GithubRepoID sql.NullString `json:"github_repo_id"`
	RawJson      string         `json:"raw_json"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRepository,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.GithubRepoID,
		arg.RawJson,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertThread = `-- name: UpsertThread :one
insert into threads(
  repo_id, github_id, number, kind, state, title, body, author_login, author_type, html_url,
  labels_json, assignees_json, raw_json, content_hash, is_draft,
  created_at_gh, updated_at_gh, closed_at_gh, merged_at_gh,
  first_pulled_at, last_pulled_at, updated_at
)
values(
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10,
  ?11, ?12, ?13, ?14, ?15,
  ?16, ?17, ?18, ?19,
  ?20, ?21, ?22
)
on conflict(repo_id, kind, number) do update set
  github_id=excluded.github_id,
  state=excluded.state,
  title=excluded.title,
  body=excluded.body,
  author_login=excluded.author_login,
  author_type=excluded.author_type,
  html_url=excluded.html_url,
  labels_json=excluded.labels_json,
  assignees_json=excluded.assignees_json,
  raw_json=excluded.raw_json,
  content_hash=excluded.content_hash,
  is_draft=excluded.is_draft,
  created_at_gh=excluded.created_at_gh,
  updated_at_gh=excluded.updated_at_gh,
  closed_at_gh=excluded.closed_at_gh,
  merged_at_gh=excluded.merged_at_gh,
  last_pulled_at=excluded.last_pulled_at,
  updated_at=excluded.updated_at
returning id
`

type UpsertThreadParams struct {
	RepoID        int64          `json:"repo_id"`
	GithubID      string         `json:"github_id"`
	Number        int64          `json:"number"`
	Kind          string         `json:"kind"`
	State         string         `json:"state"`
	Title         string         `json:"title"`
	Body          sql.NullString `json:"body"`
	AuthorLogin   sql.NullString `json:"author_login"`
	AuthorType    sql.NullString `json:"author_type"`
	HtmlUrl       string         `json:"html_url"`
	LabelsJson    string         `json:"labels_json"`
	AssigneesJson string         `json:"assignees_json"`
	RawJson       string         `json:"raw_json"`
	ContentHash   string         `json:"content_hash"`
	IsDraft       int64          `json:"is_draft"`
	CreatedAtGh   sql.NullString `json:"created_at_gh"`
	UpdatedAtGh   sql.NullString `json:"updated_at_gh"`
	ClosedAtGh    sql.NullString `json:"closed_at_gh"`
	MergedAtGh    sql.NullString `json:"merged_at_gh"`
	FirstPulledAt sql.NullString `json:"first_pulled_at"`
	LastPulledAt  sql.NullString `json:"last_pulled_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) UpsertThread(ctx context.Context, arg UpsertThreadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertThread,
		arg.RepoID,
		arg.GithubID,
		arg.Number,
		arg.Kind,
		arg.State,
		arg.Title,
		arg.Body,
		arg.AuthorLogin,
		arg.AuthorType,
		arg.HtmlUrl,
		arg.LabelsJson,
		arg.AssigneesJson,
		arg.RawJson,
		arg.ContentHash,
		arg.IsDraft,
		arg.CreatedAtGh,
		arg.UpdatedAtGh,
		arg.ClosedAtGh,
		arg.MergedAtGh,
		arg.FirstPulledAt,
		arg.LastPulledAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertWorkflowRun = `-- name: UpsertWorkflowRun :exec
insert into github_workflow_runs(repo_id, run_id, run_number, head_branch, head_sha, status, conclusion, workflow_name, event, html_url, created_at_gh, updated_at_gh, raw_json, fetched_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
on conflict(repo_id, run_id) do update set
  run_number=excluded.run_number,
  head_branch=excluded.head_branch,
  head_sha=excluded.head_sha,
  status=excluded.status,
  conclusion=excluded.conclusion,
  workflow_name=excluded.workflow_name,
  event=excluded.event,
  html_url=excluded.html_url,
  created_at_gh=excluded.created_at_gh,
  updated_at_gh=excluded.updated_at_gh,
  raw_json=excluded.raw_json,
  fetched_at=excluded.fetched_at
`

type UpsertWorkflowRunParams struct {
	RepoID       int64          `json:"repo_id"`
	RunID        string         `json:"run_id"`
	RunNumber    int64          `json:"run_number"`
	HeadBranch   sql.NullString `json:"head_branch"`
	HeadSha      sql.NullString `json:"head_sha"`
	Status       sql.NullString `json:"status"`
	Conclusion   sql.NullString `json:"conclusion"`
	WorkflowName sql.NullString `json:"workflow_name"`
	Event        sql.NullString `json:"event"`
	HtmlUrl      sql.NullString `json:"html_url"`
	CreatedAtGh  sql.NullString `json:"created_at_gh"`
	UpdatedAtGh  sql.NullString `json:"updated_at_gh"`
	RawJson      string         `json:"raw_json"`
	FetchedAt    string         `json:"fetched_at"`
}

func (q *Queries) UpsertWorkflowRun(ctx context.Context, arg UpsertWorkflowRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowRun,
		arg.RepoID,
		arg.RunID,
		arg.RunNumber,
		arg.HeadBranch,
		arg.HeadSha,
		arg.Status,
		arg.Conclusion,
		arg.WorkflowName,
		arg.Event,
		arg.HtmlUrl,
		arg.CreatedAtGh,
		arg.UpdatedAtGh,
		arg.RawJson,
		arg.FetchedAt,
	)
	return err
}
